
platform :ios, '8.0'
inhibit_all_warnings!

target 'BenzClient' do
 
pod 'Masonry', '~> 1.0.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~>3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.8.1'
pod 'MBProgressHUD', '~> 0.9.1'


end

